spring.application.name=backend
server.port=8080

# Connect to your local MySQL EmergencyDB
spring.datasource.url=jdbc:mysql://localhost:3306/emergencydb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Mi_2008_ni
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver